name = "DicePools"
uuid = "584c3e6a-265e-4f21-8a20-c21f07c48443"
authors = ["lsaenzt <59137624+lsaenzt@users.noreply.github.com>"]
version = "0.6.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
Combinatorics = "1"
OrderedCollections = "1"
Tables = "1"
julia = "1.6"
